# Generated by Django 3.2.4 on 2023-09-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_submittedtask_answer_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchtiming',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='enotes',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='mylectures',
            name='video_batch',
        ),
        migrations.RemoveField(
            model_name='mylectures',
            name='video_category',
        ),
        migrations.RemoveField(
            model_name='mytask',
            name='taskbatch',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='batch',
        ),
        migrations.DeleteModel(
            name='submittedtask',
        ),
        migrations.DeleteModel(
            name='batchtiming',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='enotes',
        ),
        migrations.DeleteModel(
            name='mylectures',
        ),
        migrations.DeleteModel(
            name='mytask',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
        migrations.DeleteModel(
            name='studentbatch',
        ),
    ]
