# Generated by Django 3.2.4 on 2023-09-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_batchtiming_category_enotes_mylectures_mytask_signup_studentbatch_submittedtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='college',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='session',
        ),
        migrations.DeleteModel(
            name='college',
        ),
        migrations.DeleteModel(
            name='placement',
        ),
    ]
