# Generated by Django 3.2.4 on 2023-09-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230927_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200, null=True)),
                ('college_pic', models.ImageField(null=True, upload_to='static/college')),
            ],
        ),
        migrations.CreateModel(
            name='placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_picture', models.ImageField(null=True, upload_to='static/placement')),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='static/company/')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.college')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.session_year')),
            ],
        ),
    ]
