# Generated by Django 3.2.4 on 2023-10-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_college_placement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
