# Generated by Django 3.2.4 on 2023-10-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='myfeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/feedbackImg/')),
            ],
        ),
    ]
